[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2018"

[lib]
name = "{{crate_name}}"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.7", features = ["extension-module"] }
