[package]
name = "fizz-buzz"
version = "0.1.0"
authors = ["Anton Patrushev <apatrushev@gmail.com>"]
edition = "2018"

[lib]
name = "fizz_buzz"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.7", features = ["extension-module"] }
